### ISSUE TITLE
main.py doubt

### ISSUE THREAD

**Issue by aritra1804** [aishmittal/Real-time-Face-Recognition-based-Surveillance-System#3]
Hey when i try to run main.py... the images are not getting captured
it shows
Face identification started ..........
Total Faces in Image = 1 
Errors occured !
can only concatenate str (not "bytes") to str

**Comment by aritra1804** [comment]
@aishmittal could u pls help

**Comment by aishmittal** [comment]
Hi, I think this error is due to either cloudinary or ms face api not working. Have ypu setup these two APIs with your user account? Steps for this are mentioned here https://github.com/aishmittal/Real-time-Face-Recognition-based-Surveillance-System#apis-used

**Comment by aritra1804** [comment]
yup i have
It would be really helpful if you could help me like in a meet or something cuz its kind as urgent as i am participating in a hackathon. That is if you dont mind
